eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8070
spring:
  application:
    name: school-service
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/schools
    hikari:
      username: postgres
      password: Cambiami123
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    students-url: http://localhost:8090/rest-api/students #url of student-service

management:
  tracing:
    sampling:
      probability: 1.0